'use client'
import {Inter} from "next/font/google";
import "./globals.css";
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import {NextIntlClientProvider} from "next-intl";

const inter = Inter({subsets: ["latin"]});

const queryClient = new QueryClient()
const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                       params: {locale}
                                   }
) {
    const loadMessages = async () => {
        let messages;
        try {
            messages = (await import(`../../../messages/${locale}.json`)).default;
        } catch (error) {
            console.log(error)
        }
        return messages;
    }
    return (
        <QueryClientProvider client={queryClient}>
            <NextIntlClientProvider locale={locale} messages={await loadMessages()}>
            <html lang={locale} className="!scroll-smooth">
            <head>
                <title>Min Thant Mg | Front-end Developer</title>
            </head>
            <body className={inter.className}>{children}</body>
            </html>
            </NextIntlClientProvider>
        </QueryClientProvider>
    );
}
